name: Xcode Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Xcode
      run: sudo xcode-select -s '/Applications/Xcode_14.2.app/Contents/Developer'
    - name: Build
      run: xcodebuild -scheme WorkoutTracker -project WorkoutTracker.xcodeproj build -allowProvisioningUpdates
    - name: Run tests
      run: xcodebuild test -scheme WorkoutTrackerTests -workspace WorkoutTracker.xcworkspace -allowProvisioningUpdates
